[Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 13
- parameter 'cheap' => true
, Match for rule 'CreateToyConveyor':
- parameter 'convId' => 4
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 18
- parameter 'cheap' => true
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 8
- parameter 'inCompType' => 1
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input2'
- parameter 'outCompId' => 8
- parameter 'outCompType' => 3
- parameter 'reqType' => 2
, Match for rule 'CreatePartConveyor':
- parameter 'convId' => 12
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 19
- parameter 'cheap' => true
, Match for rule 'CreateToyConveyor':
- parameter 'convId' => 1
, Match for rule 'CreatePartConveyor':
- parameter 'convId' => 6
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 11
- parameter 'inCompType' => 1
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input2'
- parameter 'outCompId' => 17
- parameter 'outCompType' => 3
- parameter 'reqType' => 2
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 9
- parameter 'inCompType' => 3
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input2'
- parameter 'outCompId' => 0
- parameter 'outCompType' => 9
- parameter 'reqType' => 3
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 2
- parameter 'inCompType' => 3
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input1'
- parameter 'outCompId' => 1
- parameter 'outCompType' => 2
- parameter 'reqType' => 3
, -Placeholder-
, Match for rule 'CreateToyConveyor':
- parameter 'convId' => 9
, Match for rule 'CreateToyConveyor':
- parameter 'convId' => 13
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 16
- parameter 'cheap' => false
, Match for rule 'CreateToyConveyor':
- parameter 'convId' => 10
, Match for rule 'CreateToyConveyor':
- parameter 'convId' => 3
, Match for rule 'CreateToyConveyor':
- parameter 'convId' => 5
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 1
- parameter 'cheap' => true
, Match for rule 'CreatePartConveyor':
- parameter 'convId' => 0
]