[Match for rule 'CreateSingleConveyor':
- parameter 'convId' => 20
, Match for rule 'CreateStack':
- parameter 'sid' => 18
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 19
, Match for rule 'CreateMultiConveyor':
- parameter 'convId' => 14
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 17
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 4
, Match for rule 'CreateCheapPrinter':
- parameter 'x' => 12
, Match for rule 'reconnectUnknownSlot':
- parameter 'inCompId' => 17
- parameter 'inCompType' => 1
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input2'
- parameter 'outCompId' => 0
- parameter 'outCompType' => 10
- parameter 'reqType' => 2
, Match for rule 'reconnectUnknownSlot':
- parameter 'inCompId' => 4
- parameter 'inCompType' => 1
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input'
- parameter 'outCompId' => 0
- parameter 'outCompType' => 10
- parameter 'reqType' => 2
, Match for rule 'reconnectUnknownSlot':
- parameter 'inCompId' => 14
- parameter 'inCompType' => 2
- parameter 'inSlot' => 'output2'
- parameter 'outSlot' => 'input1'
- parameter 'outCompId' => 20
- parameter 'outCompType' => 2
- parameter 'reqType' => -1
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 13
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 20
, Match for rule 'CreateCheapMachine':
- parameter 'machineId' => 2
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 19
- parameter 'inCompType' => 1
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input1'
- parameter 'outCompId' => 20
- parameter 'outCompType' => 3
- parameter 'reqType' => 2
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 5
, Match for rule 'CreateStack':
- parameter 'sid' => 11
, Match for rule 'CreateSingleConveyor':
- parameter 'convId' => 13
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 5
- parameter 'inCompType' => 1
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input1'
- parameter 'outCompId' => 20
- parameter 'outCompType' => 3
- parameter 'reqType' => 2
, Match for rule 'reconnectUnknownSlot':
- parameter 'inCompId' => 13
- parameter 'inCompType' => 2
- parameter 'inSlot' => 'output1'
- parameter 'outSlot' => 'input'
- parameter 'outCompId' => 18
- parameter 'outCompType' => 5
- parameter 'reqType' => -1
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 2
- parameter 'inCompType' => 3
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input2'
- parameter 'outCompId' => 0
- parameter 'outCompType' => 9
- parameter 'reqType' => 3
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 2
- parameter 'inCompType' => 3
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input2'
- parameter 'outCompId' => 0
- parameter 'outCompType' => 9
- parameter 'reqType' => 3
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 2
, Match for rule 'CreateCheapMachine':
- parameter 'machineId' => 6
, Match for rule 'CreateMultiConveyor':
- parameter 'convId' => 9
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 0
, Match for rule 'CreateStack':
- parameter 'sid' => 2
, -Placeholder-
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 15
, Match for rule 'CreateCheapMachine':
- parameter 'machineId' => 18
, Match for rule 'CreateCheapMachine':
- parameter 'machineId' => 11
, -Placeholder-
, -Placeholder-
, Match for rule 'CreateTurntable':
- parameter 'ttId' => 4
, -Placeholder-
, Match for rule 'CreateCheapMachine':
- parameter 'machineId' => 13
, -Placeholder-
, Match for rule 'CreateStack':
- parameter 'sid' => 17
, -Placeholder-
, Match for rule 'CreateCheapPrinter':
- parameter 'x' => 18
, Match for rule 'CreateTurntable':
- parameter 'ttId' => 3
, -Placeholder-
, Match for rule 'reconnectConveyerSlot':
- parameter 'inCompId' => 2
- parameter 'inCompType' => 5
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input1'
- parameter 'outCompId' => 14
- parameter 'outCompType' => 2
- parameter 'reqType' => -1

  Multi-rule #1:
, Match for rule 'CreateCheapPrinter':
- parameter 'x' => 7
, -Placeholder-
, -Placeholder-
, Match for rule 'CreateTurntable':
- parameter 'ttId' => 15
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 1
, Match for rule 'reconnectStackSlot':
- parameter 'inCompId' => 20
- parameter 'inCompType' => 2
- parameter 'inSlot' => 'output1'
- parameter 'outSlot' => 'input'
- parameter 'outCompId' => 2
- parameter 'outCompType' => 5
- parameter 'reqType' => -1

  Multi-rule #1:
, Match for rule 'CreateMultiConveyor':
- parameter 'convId' => 12
, Match for rule 'CreateTurntable':
- parameter 'ttId' => 11
, Match for rule 'CreateTurntable':
- parameter 'ttId' => 0
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 16
, Match for rule 'reconnectConveyerSlot':
- parameter 'inCompId' => 4
- parameter 'inCompType' => 1
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input2'
- parameter 'outCompId' => 9
- parameter 'outCompType' => 2
- parameter 'reqType' => 2

  Multi-rule #1:
, -Placeholder-
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 8
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 8
- parameter 'inCompType' => 1
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input2'
- parameter 'outCompId' => 20
- parameter 'outCompType' => 3
- parameter 'reqType' => 2
, Match for rule 'CreateCheapPrinter':
- parameter 'x' => 6
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 12
, Match for rule 'CreateTurntable':
- parameter 'ttId' => 14
, Match for rule 'CreateTurntable':
- parameter 'ttId' => 2
]