[Match for rule 'CreateCheapPrinter':
- parameter 'x' => 14
, Match for rule 'reconnectUnknownSlot':
- parameter 'inCompId' => 14
- parameter 'inCompType' => 1
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input'
- parameter 'outCompId' => 0
- parameter 'outCompType' => 10
- parameter 'reqType' => 2
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 16
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 14
- parameter 'inCompType' => 1
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input1'
- parameter 'outCompId' => 16
- parameter 'outCompType' => 3
- parameter 'reqType' => 2
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 11
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 0
, Match for rule 'CreateTurntable':
- parameter 'ttId' => 13
, Match for rule 'CreateMultiConveyor':
- parameter 'convId' => 11
, Match for rule 'CreateSingleConveyor':
- parameter 'convId' => 4
, Match for rule 'reconnectUnknownSlot':
- parameter 'inCompId' => 13
- parameter 'inCompType' => 4
- parameter 'inSlot' => 'toy'
- parameter 'outSlot' => 'input1'
- parameter 'outCompId' => 4
- parameter 'outCompType' => 2
- parameter 'reqType' => 3
, Match for rule 'reconnectUnknownSlot':
- parameter 'inCompId' => 16
- parameter 'inCompType' => 3
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input'
- parameter 'outCompId' => 13
- parameter 'outCompType' => 4
- parameter 'reqType' => 3
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 13
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 4
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 14
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 4
, Match for rule 'reconnectConveyerSlot':
- parameter 'inCompId' => 4
- parameter 'inCompType' => 3
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input2'
- parameter 'outCompId' => 11
- parameter 'outCompType' => 2
- parameter 'reqType' => 3

  Multi-rule #1:
, -Placeholder-
, -Placeholder-
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 18
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 1
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 5
, Match for rule 'CreateMultiConveyor':
- parameter 'convId' => 7
, -Placeholder-
, Match for rule 'CreateMultiConveyor':
- parameter 'convId' => 9
, Match for rule 'CreateStack':
- parameter 'sid' => 7
, Match for rule 'CreateCheapPrinter':
- parameter 'x' => 8
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 1
, Match for rule 'reconnectUnknownSlot':
- parameter 'inCompId' => 16
- parameter 'inCompType' => 3
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input'
- parameter 'outCompId' => 7
- parameter 'outCompType' => 5
- parameter 'reqType' => 3
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 1
- parameter 'inCompType' => 1
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input2'
- parameter 'outCompId' => 16
- parameter 'outCompType' => 3
- parameter 'reqType' => 2
, Match for rule 'CreateCheapMachine':
- parameter 'machineId' => 20
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 18
- parameter 'inCompType' => 1
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input2'
- parameter 'outCompId' => 16
- parameter 'outCompType' => 3
- parameter 'reqType' => 2
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 9
- parameter 'inCompType' => 2
- parameter 'inSlot' => 'output1'
- parameter 'outSlot' => 'input2'
- parameter 'outCompId' => 7
- parameter 'outCompType' => 2
- parameter 'reqType' => -1
, -Placeholder-
, Match for rule 'CreateMultiConveyor':
- parameter 'convId' => 6
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 15
, Match for rule 'reconnectConveyerSlot':
- parameter 'inCompId' => 15
- parameter 'inCompType' => 3
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input2'
- parameter 'outCompId' => 6
- parameter 'outCompType' => 2
- parameter 'reqType' => 3

  Multi-rule #1:
, Match for rule 'CreateMultiConveyor':
- parameter 'convId' => 1
, Match for rule 'CreateTurntable':
- parameter 'ttId' => 0
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 9
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 16
, Match for rule 'CreateCheapMachine':
- parameter 'machineId' => 7
, Match for rule 'CreateStack':
- parameter 'sid' => 0
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 19
, Match for rule 'CreateTurntable':
- parameter 'ttId' => 20
, Match for rule 'CreateSingleConveyor':
- parameter 'convId' => 16
, Match for rule 'reconnectUnknownSlot':
- parameter 'inCompId' => 4
- parameter 'inCompType' => 3
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input'
- parameter 'outCompId' => 0
- parameter 'outCompType' => 4
- parameter 'reqType' => 3
, Match for rule 'CreateCheapPrinter':
- parameter 'x' => 13
, -Placeholder-
, -Placeholder-
, Match for rule 'reconnectStackSlot':
- parameter 'inCompId' => 16
- parameter 'inCompType' => 2
- parameter 'inSlot' => 'output1'
- parameter 'outSlot' => 'input'
- parameter 'outCompId' => 0
- parameter 'outCompType' => 5
- parameter 'reqType' => -1

  Multi-rule #1:
, Match for rule 'CreateCheapPrinter':
- parameter 'x' => 10
, Match for rule 'CreateSingleConveyor':
- parameter 'convId' => 15
, Match for rule 'CreateCheapMachine':
- parameter 'machineId' => 17
, -Placeholder-
, -Placeholder-
, Match for rule 'CreateExpensivePrinter':
- parameter 'x' => 3
, Match for rule 'reconnectUnknownSlot':
- parameter 'inCompId' => 1
- parameter 'inCompType' => 1
- parameter 'inSlot' => 'output'
- parameter 'outSlot' => 'input1'
- parameter 'outCompId' => 15
- parameter 'outCompType' => 2
- parameter 'reqType' => 2
, Match for rule 'reconnectMatchingSlot':
- parameter 'inCompId' => 15
- parameter 'inCompType' => 2
- parameter 'inSlot' => 'output1'
- parameter 'outSlot' => 'input1'
- parameter 'outCompId' => 9
- parameter 'outCompType' => 2
- parameter 'reqType' => -1
, Match for rule 'CreateCheapPrinter':
- parameter 'x' => 6
, Match for rule 'CreateExpensiveMachine':
- parameter 'machineId' => 18
]